
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  ssl_certificate: /etc/letsencrypt/live/cz-prg-edge.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/cz-prg-edge.duckdns.org/privkey.pem

